# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_tde')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_tde')
    _tde = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_tde', [dirname(__file__)])
        except ImportError:
            import _tde
            return _tde
        try:
            _mod = imp.load_module('_tde', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _tde = swig_import_helper()
    del swig_import_helper
else:
    import _tde
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


import btk20
from btk20 import stream
oldimport = """

import btk20.stream

"""

class CCTDEPtr(btk20.stream.VectorFeatureStreamPtr):
    __swig_setmethods__ = {}
    for _s in [btk20.stream.VectorFeatureStreamPtr]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, CCTDEPtr, name, value)
    __swig_getmethods__ = {}
    for _s in [btk20.stream.VectorFeatureStreamPtr]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, CCTDEPtr, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __iter__(self):
        return _tde.CCTDEPtr___iter__(self)

    def __deref__(self):
        return _tde.CCTDEPtr___deref__(self)
    __swig_destroy__ = _tde.delete_CCTDEPtr
    __del__ = lambda self: None

    def next(self, frame_no=-5):
        return _tde.CCTDEPtr_next(self, frame_no)

    def reset(self):
        return _tde.CCTDEPtr_reset(self)

    def allsamples(self, fftLen=-1):
        return _tde.CCTDEPtr_allsamples(self, fftLen)

    def set_target_frequency_range(self, freqLowerLimit, freqUpperLimit):
        return _tde.CCTDEPtr_set_target_frequency_range(self, freqLowerLimit, freqUpperLimit)

    def sample_delays(self):
        return _tde.CCTDEPtr_sample_delays(self)

    def cc_values(self):
        return _tde.CCTDEPtr_cc_values(self)

    def name(self):
        return _tde.CCTDEPtr_name(self)

    def size(self):
        return _tde.CCTDEPtr_size(self)

    def current(self):
        return _tde.CCTDEPtr_current(self)
CCTDEPtr_swigregister = _tde.CCTDEPtr_swigregister
CCTDEPtr_swigregister(CCTDEPtr)

# This file is compatible with both classic and new-style classes.


